// lib/projectGenerator.ts
// Generates complete IDE-ready project structures for different frameworks

interface Step {
  sequence: number;
  type: string;
  url?: string;
  pageTitle?: string;
  target?: any;
  value?: string;
  key?: string;
  scrollX?: number;
  scrollY?: number;
}

interface ProjectFile {
  path: string;
  content: string;
}

interface ProjectOptions {
  workflowTitle: string;
  framework: string;
  structure: "simple" | "pom";
  steps: Step[];
}

// ─── Selector helper ──────────────────────────────────────────────────────────

function getSelector(target: any, framework: string): string {
  if (!target) return framework.includes("selenium") ? '"body"' : "'body'";
  if (target.data_testid) {
    if (framework.includes("playwright"))
      return `'[data-testid="${target.data_testid}"]'`;
    if (framework.includes("cypress"))
      return `'[data-testid="${target.data_testid}"]'`;
    if (framework === "selenium-py")
      return `By.CSS_SELECTOR, '[data-testid="${target.data_testid}"]'`;
    if (framework === "selenium-java")
      return `By.cssSelector("[data-testid=\\"${target.data_testid}\\"]")`;
  }
  if (target.aria_label) {
    if (framework.includes("playwright"))
      return `'[aria-label="${target.aria_label}"]'`;
    if (framework.includes("cypress"))
      return `'[aria-label="${target.aria_label}"]'`;
    if (framework === "selenium-py")
      return `By.XPATH, '//*[@aria-label="${target.aria_label}"]'`;
    if (framework === "selenium-java")
      return `By.xpath("//*[@aria-label=\\"${target.aria_label}\\"]")`;
  }
  if (target.id) {
    if (framework.includes("playwright")) return `'#${target.id}'`;
    if (framework.includes("cypress")) return `'#${target.id}'`;
    if (framework === "selenium-py") return `By.ID, '${target.id}'`;
    if (framework === "selenium-java") return `By.id("${target.id}")`;
  }
  if (target.css_selector) {
    if (framework.includes("playwright")) return `'${target.css_selector}'`;
    if (framework.includes("cypress")) return `'${target.css_selector}'`;
    if (framework === "selenium-py")
      return `By.CSS_SELECTOR, '${target.css_selector}'`;
    if (framework === "selenium-java")
      return `By.cssSelector("${target.css_selector}")`;
  }
  return framework.includes("selenium") ? `By.TAG_NAME, "body"` : "'body'";
}

// ─── Group steps by page ──────────────────────────────────────────────────────

function groupStepsByPage(steps: Step[]) {
  const pages: { title: string; url: string; steps: Step[] }[] = [];
  let current: { title: string; url: string; steps: Step[] } | null = null;

  for (const step of steps) {
    if (step.type === "navigate" || !current) {
      if (current) pages.push(current);
      current = {
        title: step.pageTitle || "Page",
        url: step.url || "",
        steps: [],
      };
    }
    if (current) current.steps.push(step);
  }
  if (current) pages.push(current);
  return pages;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_").replace(/^_+|_+$/g, "");
}

// ─── PLAYWRIGHT JS/TS ─────────────────────────────────────────────────────────

function generatePlaywrightSimple(opts: ProjectOptions): ProjectFile[] {
  const { workflowTitle, framework, steps } = opts;
  const isTs = framework === "playwright-ts";
  const ext = isTs ? "ts" : "js";
  const safeName = sanitizeName(workflowTitle);

  const lines: string[] = [];
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Workflow: ${workflowTitle}`);
  lines.push(` * Generated by TraceDeck`);
  lines.push(` * Structure: Simple`);
  lines.push(` * Framework: ${framework}`);
  lines.push(` */`);
  lines.push(`test('${workflowTitle}', async ({ page }) => {`);
  lines.push(``);

  for (const step of steps) {
    const sel = getSelector(step.target, framework);
    lines.push(
      `  // Step ${step.sequence}: ${step.type}${step.pageTitle ? ` — ${step.pageTitle}` : ""}`,
    );
    switch (step.type) {
      case "navigate":
        lines.push(`  await page.goto('${step.url}');`);
        break;
      case "click":
        lines.push(`  await page.locator(${sel}).click();`);
        break;
      case "dblclick":
        lines.push(`  await page.locator(${sel}).dblclick();`);
        break;
      case "type": {
        const val =
          step.value === "__SECRET__"
            ? "${process.env.SECRET}"
            : step.value || "";
        lines.push(`  await page.locator(${sel}).fill('${val}');`);
        break;
      }
      case "select":
        lines.push(
          `  await page.locator(${sel}).selectOption('${step.value}');`,
        );
        break;
      case "keypress":
        lines.push(`  await page.keyboard.press('${step.key}');`);
        break;
      case "scroll":
        lines.push(
          `  await page.evaluate(() => window.scrollTo(${step.scrollX || 0}, ${step.scrollY || 0}));`,
        );
        break;
      default:
        lines.push(`  // ${step.type} — unsupported`);
    }
    lines.push(``);
  }

  lines.push(`});`);

  const config = isTs
    ? `import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  use: {
    headless: true,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
});`
    : `const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './tests',
  use: {
    headless: true,
    screenshot: 'only-on-failure',
  },
});`;

  return [
    {
      path: `tests/${safeName}.spec.${ext}`,
      content: lines.join("\n"),
    },
    {
      path: `playwright.config.${ext}`,
      content: config,
    },
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: safeName.toLowerCase(),
          version: "1.0.0",
          description: `TraceDeck generated test: ${workflowTitle}`,
          scripts: {
            test: "playwright test",
            "test:headed": "playwright test --headed",
            "test:report": "playwright show-report",
          },
          devDependencies: {
            "@playwright/test": "^1.40.0",
            ...(isTs ? { typescript: "^5.0.0" } : {}),
          },
        },
        null,
        2,
      ),
    },
    {
      path: ".env.example",
      content: `# Environment variables for ${workflowTitle}
# Copy this file to .env and fill in your values
SECRET=your_password_here
BASE_URL=https://your-app.com
`,
    },
    {
      path: ".gitignore",
      content: `node_modules/
.env
test-results/
playwright-report/
`,
    },
    {
      path: "README.md",
      content: `# ${workflowTitle}

Generated by [TraceDeck](https://tracedeck.io)

## Setup

\`\`\`bash
npm install
npx playwright install
cp .env.example .env
# Edit .env with your credentials
\`\`\`

## Run

\`\`\`bash
npm test
\`\`\`

## View Report

\`\`\`bash
npm run test:report
\`\`\`
`,
    },
  ];
}

function generatePlaywrightPOM(opts: ProjectOptions): ProjectFile[] {
  const { workflowTitle, framework, steps } = opts;
  const isTs = framework === "playwright-ts";
  const ext = isTs ? "ts" : "js";
  const safeName = sanitizeName(workflowTitle);
  const pages = groupStepsByPage(steps);
  const files: ProjectFile[] = [];

  // Generate a page object per unique page
  const pageNames = new Set<string>();
  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    if (pageNames.has(pageName)) continue;
    pageNames.add(pageName);

    const pageLines: string[] = [];
    if (isTs) pageLines.push(`import { Page } from '@playwright/test';`);
    pageLines.push(``);
    pageLines.push(`/**`);
    pageLines.push(` * Page Object: ${page.title}`);
    pageLines.push(` * URL: ${page.url}`);
    pageLines.push(` * Generated by TraceDeck`);
    pageLines.push(` */`);

    if (isTs) {
      pageLines.push(`export class ${pageName} {`);
      pageLines.push(`  constructor(private page: Page) {}`);
    } else {
      pageLines.push(`class ${pageName} {`);
      pageLines.push(`  constructor(page) {`);
      pageLines.push(`    this.page = page;`);
      pageLines.push(`  }`);
    }
    pageLines.push(``);

    // navigate method
    pageLines.push(`  // Navigate to this page`);
    pageLines.push(`  async navigate() {`);
    pageLines.push(`    await this.page.goto('${page.url}');`);
    pageLines.push(`  }`);
    pageLines.push(``);

    // generate a method per action step
    for (const step of page.steps) {
      if (step.type === "navigate") continue;
      const sel = getSelector(step.target, framework);
      const methodName = `${step.type}${step.target?.text_content ? "_" + sanitizeName(step.target.text_content).slice(0, 20) : "_step" + step.sequence}`;

      pageLines.push(`  // Step ${step.sequence}: ${step.type}`);
      pageLines.push(`  async ${methodName}() {`);

      switch (step.type) {
        case "click":
          pageLines.push(`    await this.page.locator(${sel}).click();`);
          break;
        case "dblclick":
          pageLines.push(`    await this.page.locator(${sel}).dblclick();`);
          break;
        case "type": {
          const val =
            step.value === "__SECRET__"
              ? "process.env.SECRET"
              : `'${step.value || ""}'`;
          pageLines.push(`    await this.page.locator(${sel}).fill(${val});`);
          break;
        }
        case "select":
          pageLines.push(
            `    await this.page.locator(${sel}).selectOption('${step.value}');`,
          );
          break;
        case "keypress":
          pageLines.push(`    await this.page.keyboard.press('${step.key}');`);
          break;
        case "scroll":
          pageLines.push(
            `    await this.page.evaluate(() => window.scrollTo(${step.scrollX || 0}, ${step.scrollY || 0}));`,
          );
          break;
        default:
          pageLines.push(`    // ${step.type} not supported`);
      }

      pageLines.push(`  }`);
      pageLines.push(``);
    }

    pageLines.push(`}`);
    if (!isTs) pageLines.push(`module.exports = { ${pageName} };`);

    files.push({
      path: `pages/${pageName}.${ext}`,
      content: pageLines.join("\n"),
    });
  }

  // Generate test file
  const testLines: string[] = [];
  testLines.push(`import { test, expect } from '@playwright/test';`);
  if (isTs) {
    Array.from(pageNames).forEach((name) => {
      testLines.push(`import { ${name} } from '../pages/${name}';`);
    });
  } else {
    Array.from(pageNames).forEach((name) => {
      testLines.push(`const { ${name} } = require('../pages/${name}');`);
    });
  }
  testLines.push(``);
  testLines.push(`/**`);
  testLines.push(` * Workflow: ${workflowTitle}`);
  testLines.push(` * Structure: Page Object Model`);
  testLines.push(` * Generated by TraceDeck`);
  testLines.push(` */`);
  testLines.push(`test('${workflowTitle}', async ({ page }) => {`);
  testLines.push(``);

  Array.from(pageNames).forEach((name) => {
    const varName = name.charAt(0).toLowerCase() + name.slice(1);
    testLines.push(`  const ${varName} = new ${name}(page);`);
  });
  testLines.push(``);

  for (const pg of pages) {
    const pageName = sanitizeName(pg.title) + "Page";
    const varName = pageName.charAt(0).toLowerCase() + pageName.slice(1);
    testLines.push(`  // ${pg.title}`);
    testLines.push(`  await ${varName}.navigate();`);
    for (const step of pg.steps) {
      if (step.type === "navigate") continue;
      const methodName = `${step.type}${step.target?.text_content ? "_" + sanitizeName(step.target.text_content).slice(0, 20) : "_step" + step.sequence}`;
      testLines.push(`  await ${varName}.${methodName}();`);
    }
    testLines.push(``);
  }

  testLines.push(`});`);

  files.push({
    path: `tests/${safeName}.spec.${ext}`,
    content: testLines.join("\n"),
  });

  // Config + package.json + README
  files.push({
    path: `playwright.config.${ext}`,
    content: `import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  use: {
    headless: true,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'retain-on-failure',
  },
});`,
  });

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: safeName.toLowerCase(),
        version: "1.0.0",
        description: `TraceDeck POM project: ${workflowTitle}`,
        scripts: {
          test: "playwright test",
          "test:headed": "playwright test --headed",
          "test:report": "playwright show-report",
        },
        devDependencies: {
          "@playwright/test": "^1.40.0",
          ...(isTs ? { typescript: "^5.0.0" } : {}),
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: ".env.example",
    content: `SECRET=your_password_here\nBASE_URL=https://your-app.com\n`,
  });
  files.push({
    path: ".gitignore",
    content: `node_modules/\n.env\ntest-results/\nplaywright-report/\n`,
  });
  files.push({
    path: "README.md",
    content: `# ${workflowTitle} — POM Structure\n\nGenerated by TraceDeck\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpx playwright install\ncp .env.example .env\n\`\`\`\n\n## Run\n\n\`\`\`bash\nnpm test\n\`\`\`\n`,
  });

  return files;
}

// ─── SELENIUM JAVA ────────────────────────────────────────────────────────────

function generateSeleniumJavaPOM(opts: ProjectOptions): ProjectFile[] {
  const { workflowTitle, steps } = opts;
  const safeName = sanitizeName(workflowTitle);
  const className = safeName
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const pages = groupStepsByPage(steps);
  const files: ProjectFile[] = [];

  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    const lines: string[] = [];
    lines.push(`package com.tracedeck.pages;`);
    lines.push(``);
    lines.push(`import org.openqa.selenium.*;`);
    lines.push(`import org.openqa.selenium.interactions.Actions;`);
    lines.push(`import org.openqa.selenium.support.ui.Select;`);
    lines.push(``);
    lines.push(`/**`);
    lines.push(` * Page Object: ${page.title}`);
    lines.push(` * URL: ${page.url}`);
    lines.push(` * Generated by TraceDeck`);
    lines.push(` */`);
    lines.push(`public class ${pageName} {`);
    lines.push(`    private WebDriver driver;`);
    lines.push(``);
    lines.push(`    public ${pageName}(WebDriver driver) {`);
    lines.push(`        this.driver = driver;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    public void navigate() {`);
    lines.push(`        driver.get("${page.url}");`);
    lines.push(`    }`);
    lines.push(``);

    for (const step of page.steps) {
      if (step.type === "navigate") continue;
      const sel = getSelector(step.target, "selenium-java");
      const methodName = `${step.type}${step.target?.text_content ? sanitizeName(step.target.text_content).slice(0, 20) : "Step" + step.sequence}`;

      lines.push(`    // Step ${step.sequence}: ${step.type}`);
      lines.push(`    public void ${methodName}() {`);

      switch (step.type) {
        case "click":
          lines.push(`        driver.findElement(${sel}).click();`);
          break;
        case "type": {
          const val =
            step.value === "__SECRET__"
              ? `System.getenv("SECRET")`
              : `"${step.value || ""}"`;
          lines.push(`        WebElement el = driver.findElement(${sel});`);
          lines.push(`        el.clear();`);
          lines.push(`        el.sendKeys(${val});`);
          break;
        }
        case "select":
          lines.push(
            `        new Select(driver.findElement(${sel})).selectByVisibleText("${step.value}");`,
          );
          break;
        case "scroll":
          lines.push(
            `        ((JavascriptExecutor) driver).executeScript("window.scrollTo(${step.scrollX || 0}, ${step.scrollY || 0})");`,
          );
          break;
        default:
          lines.push(`        // ${step.type} not supported`);
      }

      lines.push(`    }`);
      lines.push(``);
    }

    lines.push(`}`);
    files.push({
      path: `src/test/java/com/tracedeck/pages/${pageName}.java`,
      content: lines.join("\n"),
    });
  }

  // Test class
  const testLines: string[] = [];
  testLines.push(`package com.tracedeck.tests;`);
  testLines.push(``);
  testLines.push(`import com.tracedeck.pages.*;`);
  testLines.push(`import org.junit.jupiter.api.*;`);
  testLines.push(`import org.openqa.selenium.*;`);
  testLines.push(`import org.openqa.selenium.chrome.ChromeDriver;`);
  testLines.push(``);
  testLines.push(`/**`);
  testLines.push(` * Workflow: ${workflowTitle}`);
  testLines.push(` * Structure: Page Object Model`);
  testLines.push(` * Generated by TraceDeck`);
  testLines.push(` */`);
  testLines.push(`public class ${className}Test {`);
  testLines.push(`    private static WebDriver driver;`);
  testLines.push(``);
  testLines.push(`    @BeforeAll`);
  testLines.push(`    static void setup() {`);
  testLines.push(`        driver = new ChromeDriver();`);
  testLines.push(`        driver.manage().window().maximize();`);
  testLines.push(`    }`);
  testLines.push(``);
  testLines.push(`    @Test`);
  testLines.push(`    void test${className}() {`);

  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    const varName = pageName.charAt(0).toLowerCase() + pageName.slice(1);
    testLines.push(`        ${pageName} ${varName} = new ${pageName}(driver);`);
    testLines.push(`        ${varName}.navigate();`);
    for (const step of page.steps) {
      if (step.type === "navigate") continue;
      const methodName = `${step.type}${step.target?.text_content ? sanitizeName(step.target.text_content).slice(0, 20) : "Step" + step.sequence}`;
      testLines.push(`        ${varName}.${methodName}();`);
    }
    testLines.push(``);
  }

  testLines.push(`    }`);
  testLines.push(``);
  testLines.push(`    @AfterAll`);
  testLines.push(`    static void teardown() {`);
  testLines.push(`        if (driver != null) driver.quit();`);
  testLines.push(`    }`);
  testLines.push(`}`);

  files.push({
    path: `src/test/java/com/tracedeck/tests/${className}Test.java`,
    content: testLines.join("\n"),
  });

  // pom.xml
  files.push({
    path: "pom.xml",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tracedeck</groupId>
    <artifactId>${safeName.toLowerCase()}</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.18.1</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <useModulePath>false</useModulePath>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>`,
  });

  files.push({ path: ".env.example", content: `SECRET=your_password_here\n` });
  files.push({ path: ".gitignore", content: `target/\n.env\n*.class\n` });
  files.push({
    path: "README.md",
    content: `# ${workflowTitle}\n\nGenerated by TraceDeck — Selenium Java POM\n\n## Run\n\n\`\`\`bash\nmvn clean test\n\`\`\`\n`,
  });

  return files;
}

// ─── SELENIUM PYTHON ──────────────────────────────────────────────────────────

function generateSeleniumPythonPOM(opts: ProjectOptions): ProjectFile[] {
  const { workflowTitle, steps } = opts;
  const safeName = sanitizeName(workflowTitle).toLowerCase();
  const pages = groupStepsByPage(steps);
  const files: ProjectFile[] = [];

  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    const lines: string[] = [];
    lines.push(`from selenium.webdriver.common.by import By`);
    lines.push(`from selenium.webdriver.support.select import Select`);
    lines.push(``);
    lines.push(`# Page Object: ${page.title}`);
    lines.push(`# URL: ${page.url}`);
    lines.push(`# Generated by TraceDeck`);
    lines.push(``);
    lines.push(`class ${pageName}:`);
    lines.push(`    def __init__(self, driver):`);
    lines.push(`        self.driver = driver`);
    lines.push(``);
    lines.push(`    def navigate(self):`);
    lines.push(`        self.driver.get("${page.url}")`);
    lines.push(``);

    for (const step of page.steps) {
      if (step.type === "navigate") continue;
      const sel = getSelector(step.target, "selenium-py");
      const methodName = `${step.type}_${step.target?.text_content ? sanitizeName(step.target.text_content).toLowerCase().slice(0, 20) : "step_" + step.sequence}`;

      lines.push(`    # Step ${step.sequence}: ${step.type}`);
      lines.push(`    def ${methodName}(self):`);

      switch (step.type) {
        case "click":
          lines.push(`        self.driver.find_element(${sel}).click()`);
          break;
        case "type": {
          const val =
            step.value === "__SECRET__"
              ? `os.environ["SECRET"]`
              : `"${step.value || ""}"`;
          lines.push(`        el = self.driver.find_element(${sel})`);
          lines.push(`        el.clear()`);
          lines.push(`        el.send_keys(${val})`);
          break;
        }
        case "select":
          lines.push(
            `        Select(self.driver.find_element(${sel})).select_by_visible_text("${step.value}")`,
          );
          break;
        case "scroll":
          lines.push(
            `        self.driver.execute_script("window.scrollTo(${step.scrollX || 0}, ${step.scrollY || 0})")`,
          );
          break;
        default:
          lines.push(`        pass  # ${step.type} not supported`);
      }
      lines.push(``);
    }

    files.push({ path: `pages/${pageName}.py`, content: lines.join("\n") });
  }

  // Test file
  const testLines: string[] = [];
  testLines.push(`import os`);
  testLines.push(`import pytest`);
  testLines.push(`from selenium import webdriver`);
  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    testLines.push(`from pages.${pageName} import ${pageName}`);
  }
  testLines.push(``);
  testLines.push(`# Workflow: ${workflowTitle}`);
  testLines.push(`# Generated by TraceDeck`);
  testLines.push(``);
  testLines.push(`@pytest.fixture`);
  testLines.push(`def driver():`);
  testLines.push(`    d = webdriver.Chrome()`);
  testLines.push(`    d.implicitly_wait(10)`);
  testLines.push(`    yield d`);
  testLines.push(`    d.quit()`);
  testLines.push(``);
  testLines.push(`def test_${safeName}(driver):`);

  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    const varName = pageName.toLowerCase();
    testLines.push(`    ${varName} = ${pageName}(driver)`);
    testLines.push(`    ${varName}.navigate()`);
    for (const step of page.steps) {
      if (step.type === "navigate") continue;
      const methodName = `${step.type}_${step.target?.text_content ? sanitizeName(step.target.text_content).toLowerCase().slice(0, 20) : "step_" + step.sequence}`;
      testLines.push(`    ${varName}.${methodName}()`);
    }
    testLines.push(``);
  }

  files.push({
    path: `tests/test_${safeName}.py`,
    content: testLines.join("\n"),
  });
  files.push({
    path: "requirements.txt",
    content: `selenium==4.18.1\npytest==8.0.0\nwebdriver-manager==4.0.1\npython-dotenv==1.0.0\n`,
  });
  files.push({ path: ".env.example", content: `SECRET=your_password_here\n` });
  files.push({
    path: ".gitignore",
    content: `.env\n__pycache__/\n.pytest_cache/\n`,
  });
  files.push({
    path: "README.md",
    content: `# ${workflowTitle}\n\nGenerated by TraceDeck\n\n## Run\n\n\`\`\`bash\npip install -r requirements.txt\npytest tests/\n\`\`\`\n`,
  });

  return files;
}

// ─── CYPRESS ─────────────────────────────────────────────────────────────────

function generateCypressPOM(opts: ProjectOptions): ProjectFile[] {
  const { workflowTitle, steps } = opts;
  const safeName = sanitizeName(workflowTitle);
  const pages = groupStepsByPage(steps);
  const files: ProjectFile[] = [];

  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    const lines: string[] = [];
    lines.push(`// Page Object: ${page.title}`);
    lines.push(`// Generated by TraceDeck`);
    lines.push(``);
    lines.push(`class ${pageName} {`);
    lines.push(`  navigate() {`);
    lines.push(`    cy.visit('${page.url}');`);
    lines.push(`  }`);
    lines.push(``);

    for (const step of page.steps) {
      if (step.type === "navigate") continue;
      const sel = getSelector(step.target, "cypress-js");
      const methodName = `${step.type}${step.target?.text_content ? sanitizeName(step.target.text_content).slice(0, 20) : "Step" + step.sequence}`;

      lines.push(`  // Step ${step.sequence}: ${step.type}`);
      lines.push(`  ${methodName}() {`);

      switch (step.type) {
        case "click":
          lines.push(`    cy.get(${sel}).click();`);
          break;
        case "type": {
          const val =
            step.value === "__SECRET__"
              ? `Cypress.env('SECRET')`
              : `'${step.value || ""}'`;
          lines.push(`    cy.get(${sel}).clear().type(${val});`);
          break;
        }
        case "select":
          lines.push(`    cy.get(${sel}).select('${step.value}');`);
          break;
        case "keypress":
          lines.push(
            `    cy.focused().type('{${(step.key || "").toLowerCase()}}');`,
          );
          break;
        case "scroll":
          lines.push(
            `    cy.scrollTo(${step.scrollX || 0}, ${step.scrollY || 0});`,
          );
          break;
        default:
          lines.push(`    // ${step.type} not supported`);
      }

      lines.push(`  }`);
      lines.push(``);
    }

    lines.push(`}`);
    lines.push(`export default ${pageName};`);
    files.push({
      path: `cypress/pages/${pageName}.js`,
      content: lines.join("\n"),
    });
  }

  // Test file
  const testLines: string[] = [];
  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    testLines.push(`import ${pageName} from '../pages/${pageName}';`);
  }
  testLines.push(``);
  testLines.push(`// Workflow: ${workflowTitle}`);
  testLines.push(`// Generated by TraceDeck`);
  testLines.push(``);
  testLines.push(`describe('${workflowTitle}', () => {`);
  testLines.push(`  it('should complete the recorded workflow', () => {`);

  for (const page of pages) {
    const pageName = sanitizeName(page.title) + "Page";
    const varName = pageName.charAt(0).toLowerCase() + pageName.slice(1);
    testLines.push(`    const ${varName} = new ${pageName}();`);
    testLines.push(`    ${varName}.navigate();`);
    for (const step of page.steps) {
      if (step.type === "navigate") continue;
      const methodName = `${step.type}${step.target?.text_content ? sanitizeName(step.target.text_content).slice(0, 20) : "Step" + step.sequence}`;
      testLines.push(`    ${varName}.${methodName}();`);
    }
    testLines.push(``);
  }

  testLines.push(`  });`);
  testLines.push(`});`);

  files.push({
    path: `cypress/e2e/${safeName}.cy.js`,
    content: testLines.join("\n"),
  });
  files.push({
    path: "cypress.config.js",
    content: `const { defineConfig } = require('cypress');

module.exports = defineConfig({
  e2e: {
    specPattern: 'cypress/e2e/**/*.cy.js',
    screenshotOnRunFailure: true,
    video: true,
  },
  env: {
    SECRET: '',
  },
});`,
  });
  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: safeName.toLowerCase(),
        version: "1.0.0",
        scripts: { test: "cypress run", "test:open": "cypress open" },
        devDependencies: { cypress: "^13.0.0" },
      },
      null,
      2,
    ),
  });
  files.push({ path: ".env.example", content: `SECRET=your_password_here\n` });
  files.push({
    path: ".gitignore",
    content: `node_modules/\ncypress/videos/\ncypress/screenshots/\n`,
  });
  files.push({
    path: "README.md",
    content: `# ${workflowTitle}\n\nGenerated by TraceDeck\n\n## Run\n\n\`\`\`bash\nnpm install\nnpm test\n\`\`\`\n`,
  });

  return files;
}

// ─── Main export function ─────────────────────────────────────────────────────

export function generateProject(opts: ProjectOptions): ProjectFile[] {
  const { framework, structure } = opts;

  if (structure === "simple") {
    if (framework === "playwright-js" || framework === "playwright-ts") {
      return generatePlaywrightSimple(opts);
    }
    // For simple structure on other frameworks, fall through to POM
  }

  switch (framework) {
    case "playwright-js":
    case "playwright-ts":
      return generatePlaywrightPOM(opts);
    case "playwright-py":
      return generateSeleniumPythonPOM({ ...opts, framework: "playwright-py" });
    case "selenium-java":
      return generateSeleniumJavaPOM(opts);
    case "selenium-py":
      return generateSeleniumPythonPOM(opts);
    case "cypress-js":
      return generateCypressPOM(opts);
    default:
      return generatePlaywrightSimple(opts);
  }
}
